<option <?php if($country == "Albania")     {echo "selected";} ?> value="Albania">Albania</option>
<option <?php if($country == "Austria")     {echo "selected";} ?> value="Austria">Austria</option>
<option <?php if($country == "Belarus")     {echo "selected";} ?> value="Belarus">Belarus</option>
<option <?php if($country == "Belgium")     {echo "selected";} ?> value="Belgium">Belgium</option>
<option <?php if($country == "Bosnia_Herzegovina") {echo "selected";} ?> value="Bosnia_Herzegovina">Bosnia & Herzegovina</option>
<option <?php if($country == "Bulgaria")    {echo "selected";} ?> value="Bulgaria">Bulgaria</option>
<option <?php if($country == "Croatia")     {echo "selected";} ?> value="Croatia">Croatia</option>
<option <?php if($country == "Cyprus")      {echo "selected";} ?> value="Cyprus">Cyprus</option>
<option <?php if($country == "Czech")       {echo "selected";} ?> value="Czech">Czech</option>
<option <?php if($country == "Denmark")     {echo "selected";} ?> value="Denmark">Denmark</option>
<option <?php if($country == "Estonia")     {echo "selected";} ?> value="Estonia">Estonia</option>
<option <?php if($country == "Finland")     {echo "selected";} ?> value="Finland">Finland</option>
<option <?php if($country == "France")      {echo "selected";} ?> value="France">France</option>
<option <?php if($country == "Georgia")     {echo "selected";} ?> value="Georgia">Georgia</option>
<option <?php if($country == "Germany")     {echo "selected";} ?> value="Germany">Germany</option>
<option <?php if($country == "Greece")      {echo "selected";} ?> value="Greece">Greece</option>
<option <?php if($country == "Hungary")     {echo "selected";} ?> value="Hungary">Hungary</option>
<option <?php if($country == "Iceland")     {echo "selected";} ?> value="Iceland">Iceland</option>
<option <?php if($country == "Ireland")     {echo "selected";} ?> value="Ireland">Ireland</option>
<option <?php if($country == "Italy")       {echo "selected";} ?> value="Italy">Italy</option>
<option <?php if($country == "Latvia")      {echo "selected";} ?> value="Latvia">Latvia</option>
<option <?php if($country == "Liechtenstein") {echo "selected";} ?> value="Liechtenstein">Liechtenstein</option>
<option <?php if($country == "Lithuania")   {echo "selected";} ?> value="Lithuania">Lithuania</option>
<option <?php if($country == "Luxemburg")   {echo "selected";} ?> value="Luxembourg">Luxembourg</option>
<option <?php if($country == "Fyrom")       {echo "selected";} ?> value="Fyrom">Fyrom</option>
<option <?php if($country == "Malta")       {echo "selected";} ?> value="Malta">Malta</option>
<option <?php if($country == "Moldova")     {echo "selected";} ?> value="Moldova">Moldova</option>
<option <?php if($country == "Monaco")      {echo "selected";} ?> value="Monaco">Monaco</option>
<option <?php if($country == "Montenegro")  {echo "selected";} ?> value="Montenegro">Montenegro</option>
<option <?php if($country == "Netherlands") {echo "selected";} ?> value="Netherlands">Netherlands</option>
<option <?php if($country == "Norway")      {echo "selected";} ?> value="Norway">Norway</option>
<option <?php if($country == "Poland")      {echo "selected";} ?> value="Poland">Poland</option>
<option <?php if($country == "Portugal")    {echo "selected";} ?> value="Portugal">Portugal</option>
<option <?php if($country == "Romania")     {echo "selected";} ?> value="Romania">Romania</option>
<option <?php if($country == "Russia")      {echo "selected";} ?> value="Russia">Russia</option>
<option <?php if($country == "San_Marino")  {echo "selected";} ?> value="San_Marino">San Marino</option>
<option <?php if($country == "serbia")      {echo "selected";} ?> value="Serbia">Serbia</option>
<option <?php if($country == "Slovakia")    {echo "selected";} ?> value="Slovakia">Slovakia</option>
<option <?php if($country == "Slovenia")    {echo "selected";} ?> value="Slovenia">Slovenia</option>
<option <?php if($country == "Spain")       {echo "selected";} ?> value="Spain">Spain</option>
<option <?php if($country == "Sweden")      {echo "selected";} ?> value="Sweden">Sweden</option>
<option <?php if($country == "Switzerland") {echo "selected";} ?> value="Switzerland">Switzerland</option>
<option <?php if($country == "Turkey")      {echo "selected";} ?> value="Turkey">Turkey</option>
<option <?php if($country == "Ukraine")     {echo "selected";} ?> value="Ukraine">Ukraine</option>
<option <?php if($country == "UK")          {echo "selected";} ?> value="UK">UK</option>
<option <?php if($country == "Non_European"){echo "selected";} ?> value="Non_European">Non European</option>